final/config/routes.rb
Rails.application.routes.draw do
  resources :presentations
  resources :team_members
  resources :teams
  resources :surveys
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "static_pages/home"

  get "teams_index" => "teams#index"
  get "presentations_index" => "presentations#index"
  get "presentations_show" => "presentations#show"
  get "presentations_new" => "presentations#new"
  get "team_members_new" => "team_members#new"
  get "team_members_show" => "team_members#show"
  get "surveys_new" => "surveys#new"
  get "surveys_show" => "surveys#show"
  get "surveys_index" => "surveys#index"

  root "static_pages#home"
end

final/app/models/team_member.rb
class TeamMember < ApplicationRecord
    validates :user_id, uniqueness: { scope: :team_id, 
        message: "User is already a member of this team!"
    }

    belongs_to :user
    belongs_to :team
end

final/app/controllers/team_members_controller.rb
class TeamMembersController < ApplicationController
  before_action :set_team_member, only: %i[ show edit update destroy ]

  # GET /team_members or /team_members.json
  def index
    @team_members = TeamMember.all
  end

  # GET /team_members/1 or /team_members/1.json
  def show
  end

  # GET /team_members/new
  def new
    @team_member = TeamMember.new
  end

  # GET /team_members/1/edit
  def edit
  end

  # POST /team_members or /team_members.json
  def create
    @team_member = TeamMember.new(team_member_params)

    respond_to do |format|
      if @team_member.save
        format.html { redirect_to @team_member, notice: "Team member was successfully created." }
        format.json { render :show, status: :created, location: @team_member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_members/1 or /team_members/1.json
  def update
    respond_to do |format|
      if @team_member.update(team_member_params)
        format.html { redirect_to @team_member, notice: "Team member was successfully updated." }
        format.json { render :show, status: :ok, location: @team_member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_members/1 or /team_members/1.json
  def destroy
    @team_member.destroy
    respond_to do |format|
      format.html { redirect_to team_members_url, notice: "Team member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_member
      @team_member = TeamMember.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_member_params
      params.require(:team_member).permit(:user_id, :team_id)
    end
end

final/app/helpers/team_members_helper.rb
module TeamMembersHelper
end

final/app/views/team_members/_form.html.erb
<%= form_with(model: team_member, local: true) do |form| %>
  <% if team_member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(team_member.errors.count, "error") %> prohibited this team_member from being saved:</h2>

      <ul>
        <% team_member.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "User" %>
    <%= form.collection_select(:user_id, User.all, :id, :email, :promt => true) %>
  </div>

  <div class="field">
    <%= form.label "Team" %>
    <%= form.collection_select(:team_id, Team.all, :id, :name, :promt => true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

final/app/views/team_members/edit.html.erb
<h1>Editing Team Member</h1>

<%= render 'form', team_member: @team_member %>

<%= link_to 'Show', @team_member %> |
<%= link_to 'Back', team_members_path %>

final/app/views/team_members/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Team Members</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_members.each do |team_member| %>
      <tr>
        <td><%= link_to 'Show', team_member %></td>
        <td><%= link_to 'Edit', edit_team_member_path(team_member) %></td>
        <td><%= link_to 'Destroy', team_member, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team Member', new_team_member_path %>

final/app/views/team_members/new.html.erb
<h1>New Team Member</h1>

<%= render 'form', team_member: @team_member %>

<%= link_to 'Back', team_members_path %>

final/app/views/team_members/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_team_member_path(@team_member) %> |
<%= link_to 'Back', team_members_path %>