final/config/routes.rb
Rails.application.routes.draw do
  resources :presentations
  resources :team_members
  resources :teams
  resources :surveys
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "static_pages/home"

  get "teams_index" => "teams#index"
  get "presentations_index" => "presentations#index"
  get "presentations_show" => "presentations#show"
  get "presentations_new" => "presentations#new"
  get "team_members_new" => "team_members#new"
  get "team_members_show" => "team_members#show"
  get "surveys_new" => "surveys#new"
  get "surveys_show" => "surveys#show"
  get "surveys_index" => "surveys#index"

  root "static_pages#home"
end

final/app/views/layouts/_nav_bar.html.erb
<div id="nav_bar">
    <div class="site_title">
        <h1>Survey Source</h1>
    </div>

    <div class="nav_elements">
        <ul>
            <% if user_signed_in? && current_user.admin == true %>

                <li class="nav_item">
                    <%= link_to "Home", root_path %>
                </li>
                <li class="nav_item">
                    <%= link_to "Teams", teams_index_path %>
                </li>

                <li class="nav_item">
                    <%= link_to "Presentations", presentations_index_path %>
                </li>

                <li class="nav_item">
                    <%= link_to "Surveys", surveys_index_path %>
                </li>
                
                <li class="nav_item">
                    <%= link_to "Add to Team", team_members_new_path %>
                </li>

                <div class="signout_link">
                    <li class="nav_item">
                        <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
                    </li>
                </div>
            <% elsif user_signed_in? %>
                        
                <li class="nav_item">
                    <%= link_to "Home", root_path %>
                </li>
                
                <li class="nav_item">
                    <%= link_to "Presentations", presentations_index_path %>
                </li>

                <div class="signout_link">
                    <li class="nav_item">
                        <%= link_to "Sign Out", destroy_user_session_path, :method => :delete %>
                    </li>
                </div>
            <% else %>

                

                <li class="nav_item">
                    <%= link_to "Sign Up", new_user_registration_path %>
                </li>

                <div class="signout_link">
                    <li class="nav_item">
                        <%= link_to "Sign In", user_session_path %>
                    </li>
                </div>

            <% end %>
        </ul>
    </div>
</div>

final/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project6</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/nav_bar" %>
    
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <%= yield %>
  </body>
</html>