final/config/routes.rb
Rails.application.routes.draw do
  resources :presentations
  resources :team_members
  resources :teams
  resources :surveys
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "static_pages/home"

  get "teams_index" => "teams#index"
  get "presentations_index" => "presentations#index"
  get "presentations_show" => "presentations#show"
  get "presentations_new" => "presentations#new"
  get "team_members_new" => "team_members#new"
  get "team_members_show" => "team_members#show"
  get "surveys_new" => "surveys#new"
  get "surveys_show" => "surveys#show"
  get "surveys_index" => "surveys#index"

  root "static_pages#home"
end

final/app/models/survey.rb
class Survey < ApplicationRecord
    include ActiveModel::Validations

    validates :user_id, uniqueness: { scope: :presentation_id,
        message: "You have already completed a survey for this presentation!"
    }
    validates_with SurveyValidator

    belongs_to :user
    belongs_to :presentation
end

final/app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :set_survey, only: %i[ show edit update destroy ]

  # GET /surveys or /surveys.json
  def index
    @surveys = Survey.all
    @users = User.all
  end

  # GET /surveys/1 or /surveys/1.json
  def show
  end

  # GET /surveys/new
  def new
    @survey = Survey.new
  end

  # GET /surveys/1/edit
  def edit
  end

  # POST /surveys or /surveys.json
  def create
    @survey = Survey.new(survey_params)

    respond_to do |format|
      if @survey.save
        format.html { redirect_to @survey, notice: "Survey was successfully created." }
        format.json { render :show, status: :created, location: @survey }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /surveys/1 or /surveys/1.json
  def update
    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to @survey, notice: "Survey was successfully updated." }
        format.json { render :show, status: :ok, location: @survey }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @survey.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /surveys/1 or /surveys/1.json
  def destroy
    @survey.destroy
    respond_to do |format|
      format.html { redirect_to surveys_url, notice: "Survey was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_survey
      @survey = Survey.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def survey_params
      params.require(:survey).permit(:presentation_id, :comments, :overall, :organization_1, :organization_2, :organization_3, :organization_4, :organization_5, :organization_6, :organization_7, :content_1, :content_2, :content_3, :content_4, :visuals_1, :visuals_2, :visuals_3, :visuals_4, :visuals_5, :delivery_1, :delivery_2, :delivery_3).merge(user_id: current_user.id)
    end
end

final/app/helpers/surveys_helper.rb
module SurveysHelper
end

final/app/views/surveys/edit.html.erb
<h1>Editing Survey</h1>

<%= render 'form', survey: @survey %>

<%= link_to 'Show', @survey %> |
<%= link_to 'Back', surveys_path %>

final/app/views/surveys/index.html.erb
<div id="survey_index_page">
    <h2>Surveys</h2>

    <% @users.each do |user| %>
      <div class="user_survey_display">
        <div class="user_display_header">
            <div><h3><%= user.email %></h3></div>
        </div>
        <% user.surveys.each do |survey| %>
          <div class="user_survey_display_element">
              <div><h3><%= survey.presentation.name %></h3></div>
              <div><%= link_to "View Feedback", survey %></div>
          </div>
        <% end %>
      </div>
    <% end %>
</div>

final/app/views/surveys/new.html.erb
<h1>New Survey</h1>

<%= render 'form', survey: @survey %>

final/app/views/surveys/show.html.erb
<div id="survey_display">
    <h2>Survey for "<%= @survey.presentation.name %>"</h2>
    <% if current_user.admin == true %>
        <h3>By <%= @survey.user.email %>
    <% end %>
    <table class="survey_response_table">
        <tr>
            <th>Presentation Organization</th>
            <th>Response</th>
        </tr>

        <tr>
            <td>The introduction gave me a clear idea of the topic.</td>
            <td><%= @survey.organization_1 %></td>
        </tr>

        <tr>
            <td>The introduction gave me a clear idea of the direction the presentation would take.</td>
            <td><%= @survey.organization_2 %></td>
        </tr>

        <tr>
            <td>The presentation presented information in logical, interesting sequence.</td>
            <td><%= @survey.organization_3 %></td>
        </tr>

        <tr>
            <td>The conclusion did a good job of summarizing the content of the presentation.</td>
            <td><%= @survey.organization_4 %></td>
        </tr>

        <tr>
            <td>Enough essential information was given to allow me to effectively evaluate the topic.</td>
            <td><%= @survey.organization_5 %></td>
        </tr>

        <tr>
            <td>The presentation was free from irrelevant or filler information.</td>
            <td><%= @survey.organization_6 %></td>
        </tr>

        <tr>
            <td>The presentation filled the time allotted.</td>
            <td><%= @survey.organization_7 %></td>
        </tr>
        
    </table>

    <table class="survey_response_table">
        <tr>
            <th>Presentation Content</th>
            <th>Response</th>
        </tr>

        <tr>
            <td>I could easily follow the main points of the presentation.</td>
            <td><%= @survey.content_1 %></td>
        </tr>

        <tr>
            <td>The presenter had a clear understanding of the material presented.</td>
            <td><%= @survey.content_2 %></td>
        </tr>

        <tr>
            <td>The plans, recommendations and/or conclusions are consistent with the findings.</td>
            <td><%= @survey.content_3 %></td>
        </tr>

        <tr>
            <td>Presenter answers all questions with explanations and elaboration.</td>
            <td><%= @survey.content_4 %></td>
        </tr>

    </table>

    <table class="survey_response_table">
        <tr>
            <th>Presentation Visuals</th>
            <th>Response</th>
        </tr>

        <tr>
            <td>The visuals were effective in enhancing the message.</td>
            <td><%= @survey.visuals_1 %></td>
        </tr>

        <tr>
            <td>The visuals were legible and easy to read.</td>
            <td><%= @survey.visuals_2 %></td>
        </tr>

        <tr>
            <td>Visuals were free from grammar and formatting errors.</td>
            <td><%= @survey.visuals_3 %></td>
        </tr>

        <tr>
            <td>The number of visual aids enhanced the presentation.</td>
            <td><%= @survey.visuals_4 %></td>
        </tr>

        <tr>
            <td>The visuals were displayed for an appropriate time and had no annoying transition effect.</td>
            <td><%= @survey.visuals_5 %></td>
        </tr>

    </table>

    <table class="survey_response_table">
        <tr>
            <th>Presentation Delivery</th>
            <th>Response</th>
        </tr>

        <tr>
            <td>The presenter spoke clearly, was easily heard, and maintained an appropriate talking rate.</td>
            <td><%= @survey.delivery_1 %></td>
        </tr>

        <tr>
            <td>The presenter maintained a good posture and made effective use of hand and body gesture.</td>
            <td><%= @survey.delivery_2 %></td>
        </tr>

        <tr>
            <td>The presenter maintained eye contact with the audience.</td>
            <td><%= @survey.delivery_3 %></td>
        </tr>

    </table>

    <p>Overall, this user rated the quality of the presentation as: <%= @survey.overall %><p>
    <p>Additional comments: <%= @survey.comments %>

</div>