final/config/routes.rb
Rails.application.routes.draw do
  resources :presentations
  resources :team_members
  resources :teams
  resources :surveys
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get "static_pages/home"

  get "teams_index" => "teams#index"
  get "presentations_index" => "presentations#index"
  get "presentations_show" => "presentations#show"
  get "presentations_new" => "presentations#new"
  get "team_members_new" => "team_members#new"
  get "team_members_show" => "team_members#show"
  get "surveys_new" => "surveys#new"
  get "surveys_show" => "surveys#show"
  get "surveys_index" => "surveys#index"

  root "static_pages#home"
end

final/app/models/presentation.rb
class Presentation < ApplicationRecord
    belongs_to :team
    has_many :surveys
end

final/app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_action :set_presentation, only: %i[ show edit update destroy ]

  # GET /presentations or /presentations.json
  def index
    @presentations = Presentation.all
    @teams = Team.all
  end

  # GET /presentations/1 or /presentations/1.json
  def show
  end

  # GET /presentations/new
  def new
    @presentation = Presentation.new
  end

  # GET /presentations/1/edit
  def edit
  end

  # POST /presentations or /presentations.json
  def create
    @presentation = Presentation.new(presentation_params)

    respond_to do |format|
      if @presentation.save
        format.html { redirect_to @presentation, notice: "Presentation was successfully created." }
        format.json { render :show, status: :created, location: @presentation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /presentations/1 or /presentations/1.json
  def update
    respond_to do |format|
      if @presentation.update(presentation_params)
        format.html { redirect_to @presentation, notice: "Presentation was successfully updated." }
        format.json { render :show, status: :ok, location: @presentation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @presentation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /presentations/1 or /presentations/1.json
  def destroy
    @presentation.surveys.each do |survey|
      survey.destroy
    end
    @presentation.destroy
    respond_to do |format|
      format.html { redirect_to presentations_url, notice: "Presentation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_presentation
      @presentation = Presentation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def presentation_params
      params.require(:presentation).permit(:name, :team_id)
    end
end

final/app/helpers/presentations_helper.rb
module PresentationsHelper
end

final/app/views/presentations/_admin_display.html.erb
<div id="admin_presentations_display">
    <%= link_to 'New Presentation', new_presentation_path %>

    <br>
    <% @teams.each do |team| %>
        <div class="team_presentation_display">
        <div>
            <div><h3><%= team.name %></h3></div>
        </div>
        <% team.presentations.each do |p| %>
            <div class="presentation_display_element">
            <div><h3><%= p.name %></h3></div>
            <div><%= link_to "View", p %></div>
            <div><%= link_to "Remove", p, method: :delete, data: { confirm: "Are you sure?" } %></div>
            </div>
        <% end %>
        
        </div>

    <% end %>
</div>

final/app/views/presentations/_form.html.erb
<%= form_with(model: presentation, local: true) do |form| %>
  <% if presentation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(presentation.errors.count, "error") %> prohibited this presentation from being saved:</h2>

      <ul>
        <% presentation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label "Team" %>
    <%= form.collection_select(:team_id, Team.all, :id, :name, :promt => true) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

final/app/views/presentations/_user_display.html.erb
<div id="users_presentations_display">
    <% @teams.each do |team| %>
        <div class="team_presentation_display">
            <h2><%= team.name %></h2>
            <% team.presentations.each do |p| %>
                <div class="presentation_display_element">
                    <div><h3><%= p.name %></h3></div>
                    <div><p class="survey_status">
                    <% if current_user.surveys.exists?(:presentation_id => p.id) %>
                        <%= "Survey Complete" %>
                    <% elsif current_user.teams.exists?(:id => team.id) %>
                        <%= link_to 'View Feedback', p %>
                    <% else %>
                        <%= link_to 'Take Survey', surveys_new_path(p_id: p.id) %>
                    <% end %>
                    </p></div>
                </div>
            <% end %>
        </div>
    <% end %>
</div>

final/app/views/presentations/edit.html.erb
<h1>Editing Presentation</h1>

<%= render 'form', presentation: @presentation %>

<%= link_to 'Show', @presentation %> |
<%= link_to 'Back', presentations_path %>

final/app/views/presentations/index.html.erb
<div id="presentations_index">

<h2>Presentations</h2>

<% if current_user.admin == true %>
    <%= render "presentations/admin_display" %>
<% else %>
    <%= render "presentations/user_display" %>
<% end %>

final/app/views/presentations/new.html.erb
<h1>New Presentation</h1>

<%= render 'form', presentation: @presentation %>

<%= link_to 'Back', presentations_path %>

final/app/views/presentations/show.html.erb
<div id="presentation_show">
    <h2><%= @presentation.name %></h2>
    <h3>By <%= @presentation.team.name %></h3>

    <% @presentation.surveys.each do |survey| %>
      <div class="feedback_display_element">
        <div><h3>Overall: <%= survey.overall %></h3></div>
        <div><%= link_to "Full Results", survey %></div>
      </div>
    <% end %>
</div>